In [1]:
class Employee:
    count = 0

    def __init__(self, name, family_name, salary, dpt):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__dpt = dpt
        Employee.count += 1

    def average_salary(employees):
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.count
class FulltimeEmployee(Employee):
    def __init__(self, name, family_name, salary, dpt):
        super().__init__(name, family_name, salary, dpt)

def main():
    employees = []
    fte1 = FulltimeEmployee("vamshi", "ponugoti", 1200000, "Unknown")
    employees.append(fte1)
    fte2 = FulltimeEmployee("nikhil", "vatti", 1800000, "US")
    employees.append(fte2)
    emp1 = Employee("din", "gum", 1600000, "Sales")
    employees.append(emp1)
    emp2 = Employee("prani", "bs", 135000, "UK")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()

Average salary: 1183750.0


In [6]:
import numpy as np
v = np.random.uniform(1,20, 20)
print(v)

v = v.reshape(4, 5)
print(v)

vec = np.where(v == np.max(v, axis=1,keepdims=True), 0, v)
print(v)

[13.95178592  8.59817807 11.47772581 13.06689338  1.28648661 14.79284822
  8.99250196  4.58801208 13.16855048  1.51636295 19.58138632 11.12413205
  4.29630152  9.42867515 13.08755147 18.12431204  8.14255152 13.34386221
  8.91406769 10.22028981]
[[13.95178592  8.59817807 11.47772581 13.06689338  1.28648661]
 [14.79284822  8.99250196  4.58801208 13.16855048  1.51636295]
 [19.58138632 11.12413205  4.29630152  9.42867515 13.08755147]
 [18.12431204  8.14255152 13.34386221  8.91406769 10.22028981]]
[[13.95178592  8.59817807 11.47772581 13.06689338  1.28648661]
 [14.79284822  8.99250196  4.58801208 13.16855048  1.51636295]
 [19.58138632 11.12413205  4.29630152  9.42867515 13.08755147]
 [18.12431204  8.14255152 13.34386221  8.91406769 10.22028981]]
